<a href="https://colab.research.google.com/github/SuwareeThammakoonsate/data_viz_2022/blob/main/Copy_of_Data_Structure.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Structure (โครงสร้างข้อมูล)

เก็บข้อมูลหลายๆตัวไว้ด้วยกันอย่างเป็นระเบียบ

## ```list()```*italicized text*

In [3]:
list_a = [1,2,3,4,5,6] #[ ] square brackets

In [4]:
list_a

[1, 2, 3, 4, 5, 6]

In [5]:
list_b = ['ab',2,3.14,list_a]

In [6]:
list_b

['ab', 2, 3.14, [1, 2, 3, 4, 5, 6]]

### indexing การชี้สมาชิกใน list ด้วยเลขลำดับของ list

In [7]:
list_b[3]

[1, 2, 3, 4, 5, 6]

In [8]:
list_a[3]

4

In [9]:
list_b[3][4]

5

In [10]:
list_a[-1] #index -1 คือตัวสุดท้ายของ list

6

In [11]:
list_a[-4]

3

### การสร้าง `list()`


In [12]:
list_x1 = [] #แบบที่ 1
list_x2 = list() #แบบที่ 2

In [13]:
print(list_x1)
print(list_x2)

[]
[]


### เพิ่มสมาชิกเข้าไปใน list ด้วย `append()`




In [14]:
list_x1.append(2)

In [15]:
list_x1

[2]

In [16]:
list_x1.append(4)
print(list_x1)

[2, 4]


In [17]:
list_x1[0]

2

In [18]:
list_x1[-1]

4

In [19]:
list_x2

[]

In [20]:
list_x1.append('ha')

In [21]:
list_x1

[2, 4, 'ha']

In [22]:
list_x2.append('ha')

In [23]:
list_x2

['ha']

### ลบสมาชิกจาก list

In [24]:
list_x1.append('ha')

In [25]:
list_x1

[2, 4, 'ha', 'ha']

In [26]:
list_x1.pop()

'ha'

In [27]:
list_x1

[2, 4, 'ha']

In [28]:
list_x1.pop()
print(list_x1)

[2, 4]


In [29]:
list_x1

[2, 4]

In [30]:
list_x2.append('ha')

In [31]:
list_x2

['ha', 'ha']

In [32]:
list_x2.pop()

'ha'

In [33]:
list_x2

['ha']

In [34]:
list_x2.pop()
print(list_x2)

[]


### `len()` ตรวจสอบจำนวนสมาชิกของ list (การนับ)

In [35]:
print(list_b)
print(len(list_b))

['ab', 2, 3.14, [1, 2, 3, 4, 5, 6]]
4


In [36]:
len(list_a)

6

### String is a list of characters

In [37]:
st_stat = 'Department of Statistics, Faculty of Science'

In [38]:
st_stat[10]

' '

In [39]:
len(st_stat)

44

### List Slicing `:`

`list[จุดเริ่มต้น (ทึบ):จุดสุดท้าย (โปร่ง)]`

`list[จุดเริ่มต้น (ทึบ):จุดสุดท้าย (โปร่ง):step]`

In [40]:
list_a

[1, 2, 3, 4, 5, 6]

In [41]:
list_a[2]

3

#### : colon

In [42]:
list_a[-3:] # : colon

[4, 5, 6]

In [43]:
list_a[:4]

[1, 2, 3, 4]

In [44]:
list_a[1:4]

[2, 3, 4]

In [45]:
list_a[:]

[1, 2, 3, 4, 5, 6]

#### step

In [46]:
list_c = [1,2,3,4,5,6,7,8,9,10,11,12,13]

In [47]:
list_c[:10:]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [48]:
list_c[:10:2]

[1, 3, 5, 7, 9]

In [49]:
list_c[:10:3]

[1, 4, 7, 10]

In [50]:
list_c[::-1]

[13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]

### `range()`

In [51]:
a = list(range(21))

In [52]:
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [53]:
list(range(1,21))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

# HW2 คำนวณเวลาเป็นวินาทีของเวลาต่อไปนี้โดยใช้คำสั่ง split() ช่วย (print ออกมาให้สวยงาม)

-12:30:15

-13:41:07

-09:11:50

-21:30:15

-03:10:15

In [54]:
#01:00:00 ตัวอย่าง1

a = 1*60*60
print(a)

3600


In [55]:
#01:02:03 ตัวอย่าง2

a = 1*60*60 + (2*60) + 3
print(f'01:02:03 แปลงเป็นวิยาที ได้ {a} วินาที')

01:02:03 แปลงเป็นวิยาที ได้ 3723 วินาที


## ข้อ1 12:30:15

In [56]:
a = '12:30:15' #กำหนดให้ a เป็นเวลา 12:30:15 ซึ่งเป็น string
str_a = '12:30:15'.split(':') # แยกออกจากกันด้วย split() แต่ยังเป็น string อยู่ เลยต้องแปลงให้เป็น int ก่อน
ans1 = int(str_a[0])*60*60 + int(str_a[1])*60 + int(str_a[2]) # ทำการคูณนาทีและวินาทีเข้าไปแล้วบวกกัน
print(f'12:30:15 สามารถแปลงเป็นวินาทีได้ทั้งหมด {ans1} วินาที')

12:30:15 สามารถแปลงเป็นวินาทีได้ทั้งหมด 45015 วินาที


## ข้อ2 13:41:07

In [57]:
b = '13:41:07'
str_b ='13:41:07'.split(':')
ans2 = int(str_b[0])*60*60 + int(str_b[1])*60 + int(str_b[2]) 
print(f'13:41:07 สามารถแปลงเป็นวินาทีได้ทั้งหมด {ans2} วินาที')


13:41:07 สามารถแปลงเป็นวินาทีได้ทั้งหมด 49267 วินาที


## ข้อ3 09:11:50

In [58]:
c = '09:11:50'
str_c ='09:11:50'.split(':')
ans3 = int(str_c[0])*60*60 + int(str_c[1])*60 + int(str_c[2]) 
print(f'09:11:50 สามารถแปลงเป็นวินาทีได้ทั้งหมด {ans3} วินาที')

09:11:50 สามารถแปลงเป็นวินาทีได้ทั้งหมด 33110 วินาที


## ข้อ4 21:30:15

In [59]:
d = '21:30:15'
str_d ='21:30:15'.split(':')
ans4 = int(str_d[0])*60*60 + int(str_d[1])*60 + int(str_d[2]) 
print(f'21:30:15 สามารถแปลงเป็นวินาทีได้ทั้งหมด {ans4} วินาที')

21:30:15 สามารถแปลงเป็นวินาทีได้ทั้งหมด 77415 วินาที


## ข้อ5 03:10:15

In [60]:
e = '03:10:15'
str_e ='03:10:15'.split(':')
ans5 = int(str_e[0])*60*60 + int(str_e[1])*60 + int(str_e[2]) 
print(f'03:10:15 สามารถแปลงเป็นวินาทีได้ทั้งหมด {ans5} วินาที')

03:10:15 สามารถแปลงเป็นวินาทีได้ทั้งหมด 11415 วินาที


#Dictionary

- คล้าย list()
- index เป็นอะไรก็ได้ ไม่จำเป็นต้องเป็นตัวเลขลำดับ
- ลำดับไม่มีความสำคัญ

### สร้าง Dictionary

### การชี้สมาชิกใน Dictionaty

In [61]:
dict_a.values() # อยากรู้ว่ามีผลลัพธ์อะไรบ้าง

NameError: ignored

In [62]:
dict_a = {1:'Happy','N':'New','2022':'Year'} # { } curly brackets(วงเล็บปีกกา)

In [63]:
dict_a[1]

'Happy'

In [64]:
dict_a['N']

'New'

In [65]:
dict_a.keys() # อยากรู้ว่ามี keys อะไรอยู่บ้าง

dict_keys([1, 'N', '2022'])

### การเพิ่มสมาชิกลงไปใน Dictionary

In [66]:
dict_a[7] = 3.14 # เพิ่มสมาชิกใน Dictionary เพิ่ม 7

In [67]:
dict_a

{1: 'Happy', '2022': 'Year', 7: 3.14, 'N': 'New'}

In [68]:
dict_a['N'] = 'NNNNEEEEWWWW' # อัพเดทตัว N ใหม่

In [69]:
dict_a

{1: 'Happy', '2022': 'Year', 7: 3.14, 'N': 'NNNNEEEEWWWW'}

# Numpy Array

shape:(4,) #1แถว4หลัก 1D Array

shape:(2,3) #2แถว3หลัก 2D Array

Shape:(4,3,2) #เป็น3มิติ กว้าง3*ยาว2*สูง4 3D Array

- เก็บได้แค่ตัวเลข

- อ้างอิงโดยใช้ พิกัด (2มิติ ก็มองเป็น Matrix)

In [70]:
import numpy #importแบบที่1

### 1D Array

In [71]:
list_A = [1,2,3,4,5]

In [72]:
arr_a = numpy.array(list_A)

In [73]:
arr_a

array([1, 2, 3, 4, 5])

In [74]:
list_A

[1, 2, 3, 4, 5]

In [75]:
arr_a[0]

1

In [76]:
list_A[0]

1

In [77]:
5 * arr_a # คุณสมบัติิของ Matrix (scalar multiplication)

array([ 5, 10, 15, 20, 25])

In [78]:
5*list_A # ซ้ำกัน5รอบ

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [79]:
arr_b = numpy.array([10,20,30,40,50])

In [80]:
print(arr_a)

[1 2 3 4 5]


In [81]:
arr_a.shape #บอกให้รู้ว่ามี 1แถว 5หลัก คือมีสมาชิก 5 ตัว

(5,)

### 2D array

In [82]:
import numpy as np #importแบบที่2 ความจริงเขียนครั้งเดียวก็ได้ แต่อันนี้เขียนซ้ำให้ดูเฉยๆว่าเขียนได้หลายแบบ

In [83]:
arr2_z = np.array([[1,2,3],[4,5,6]])

In [84]:
arr2_z

array([[1, 2, 3],
       [4, 5, 6]])

In [85]:
arr2_z.shape #บอกให้รู้ว่ามี 2แถว 3หลัก 

(2, 3)

### `np.zeros()`

In [86]:
arr2_3_5_0 = np.zeros((3,5))

In [87]:
arr2_3_5_0

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [88]:
arr2_3_5_0[1,2] = 9 #เป็นการกำหนดให้แถวที่1หลักที่2เป็นเลข9

In [89]:
arr2_3_5_0

array([[0., 0., 0., 0., 0.],
       [0., 0., 9., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [90]:
arr2_3_5_0[1,2] #เป็นการชี้บอกว่าแถว1 หลัก2 เป็นตัวอะไร

9.0

In [91]:
print(list_A) # เปลี่ยนค่าใน list()
list_A[-1] = 'Chrismas'
print(list_A)

[1, 2, 3, 4, 5]
[1, 2, 3, 4, 'Chrismas']


### `np.ones()`

In [92]:
arr2_4_5_1 = np.ones((4,5))

In [93]:
arr2_4_5_1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [94]:
arr2_4_5_200 = 200*np.ones((4,5))

In [95]:
arr2_4_5_200

array([[200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200.]])

## Matrix operations

#### การบวก ลบ Matrix $M \pm N$ บวกลบตัวที่อยู่ตำแหน่งเดียวกัน

In [96]:
arr2_4_5_200 + arr2_3_5_0 #การบวกลบ Matrix shape ต้องมีขนาดเท่ากัน

ValueError: ignored

In [97]:
arr2_4_5_200 + arr2_4_5_1 #การบวกลบ Matrix shape ต้องมีขนาดเท่ากัน

array([[201., 201., 201., 201., 201.],
       [201., 201., 201., 201., 201.],
       [201., 201., 201., 201., 201.],
       [201., 201., 201., 201., 201.]])

#### การคูณ Matrix
- $aM$ scalar คูณ Matrix (scalar คูณกระจายเข้าไปทุกตัวของ Matrix)

- $M\times N$ Matrix คูณ Matrix (แถวคูณหลัก)

$aM$

In [98]:
5 * arr_a # Matrix (scalar multiplication)

array([ 5, 10, 15, 20, 25])

$M\times N$ (dot product) # แถวคูณหลัก
- (m,n) $\times$ (n,o) = (m,o)(Shape)

In [99]:
mat_a = np.array([[2,3,4],[4,6,7]])
mat_b = np.array([[1,2,5],[2,4,-7]])
mat_c = np.array([[2,3],[4,6],[7,9]]) 

In [100]:
mat_a

array([[2, 3, 4],
       [4, 6, 7]])

In [101]:
mat_b

array([[ 1,  2,  5],
       [ 2,  4, -7]])

In [102]:
mat_c

array([[2, 3],
       [4, 6],
       [7, 9]])

axc, bxc

In [103]:
np.dot(mat_a,mat_c)

array([[ 44,  60],
       [ 81, 111]])

In [104]:
np.dot(mat_b,mat_c)

array([[ 45,  60],
       [-29, -33]])

cxa, cxb

In [105]:
np.dot(mat_c,mat_a)

array([[16, 24, 29],
       [32, 48, 58],
       [50, 75, 91]])

In [106]:
mat_X = np.dot(mat_c,mat_b)
print(mat_X)

[[  8  16 -11]
 [ 16  32 -22]
 [ 25  50 -28]]


In [107]:
mat_a * mat_b #คูณตัวตำแหน่งเดียวกัน

array([[  2,   6,  20],
       [  8,  24, -49]])

### Matrix Slicing

In [108]:
mat_X[:2,:2]

array([[ 8, 16],
       [16, 32]])

# HW3

1. สร้าง array ที่เป็นรูปต้น Chrismas
2. slice เลข 1 ออกมาจาก array HW3 ด้วยการ slice แค่ครั้งเดียว

In [239]:
import numpy as np
ans = np.ones((17,11))
ans

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [240]:
ans[:,5] = 8
ans[1:20,4] = 8
ans[1:20,6] = 8
ans[2:3,3] = 8
ans[2:3,7] = 8
ans[4:7,3] = 8
ans[4:7,7] = 8
ans[5:7,2] = 8
ans[5:7,8] = 8
ans[6,1] = 8
ans[6,9] = 8
ans[7:11,3] = 8
ans[7:11,7] = 8
ans[8:11,2] = 8
ans[8:11,8] = 8
ans[9:11,1] = 8
ans[9:11,9] = 8
ans[10,0] = 8
ans[10,10] = 8
ans


array([[1., 1., 1., 1., 1., 8., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 8., 8., 8., 1., 1., 1., 1.],
       [1., 1., 1., 8., 8., 8., 8., 8., 1., 1., 1.],
       [1., 1., 1., 1., 8., 8., 8., 1., 1., 1., 1.],
       [1., 1., 1., 8., 8., 8., 8., 8., 1., 1., 1.],
       [1., 1., 8., 8., 8., 8., 8., 8., 8., 1., 1.],
       [1., 8., 8., 8., 8., 8., 8., 8., 8., 8., 1.],
       [1., 1., 1., 8., 8., 8., 8., 8., 1., 1., 1.],
       [1., 1., 8., 8., 8., 8., 8., 8., 8., 1., 1.],
       [1., 8., 8., 8., 8., 8., 8., 8., 8., 8., 1.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [1., 1., 1., 1., 8., 8., 8., 1., 1., 1., 1.],
       [1., 1., 1., 1., 8., 8., 8., 1., 1., 1., 1.],
       [1., 1., 1., 1., 8., 8., 8., 1., 1., 1., 1.],
       [1., 1., 1., 1., 8., 8., 8., 1., 1., 1., 1.],
       [1., 1., 1., 1., 8., 8., 8., 1., 1., 1., 1.],
       [1., 1., 1., 1., 8., 8., 8., 1., 1., 1., 1.]])

In [127]:
hw3 = np.zeros((10,10))
hw3

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [128]:
hw3[::4,2] = 1
hw3[::4,4] = 1
hw3[::4,6] = 1
hw3[::4,8] = 1
hw3

array([[0., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [129]:
hw3[::4,2::2]

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

# Pandas Dataframe (แยกออกไปเป็น Notebook เฉพาะ)